// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Steamship.Tech.DbContexts;

namespace Steamship.Tech.Migrations
{
    [DbContext(typeof(SteamshipContext))]
    partial class SteamshipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Steamship.Tech.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("LineManagerId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("LineManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "BackTo@TheFuture.com",
                            FirstName = "Marty",
                            LastName = "McFly"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "DunderMifflin@TheOffice.com",
                            FirstName = "Michael",
                            LastName = "Scott"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "NotSuperman@Krypton.com",
                            FirstName = "Clark",
                            LastName = "Kent",
                            LineManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 4,
                            Email = "NotBatman@Gotham.com",
                            FirstName = "Bruce",
                            LastName = "Wayne",
                            LineManagerId = 1
                        },
                        new
                        {
                            EmployeeId = 5,
                            Email = "JediMaster@DarkSide.com",
                            FirstName = "Darth",
                            LastName = "Vader"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Email = "TheKingInTheNorth@Winterfell.com",
                            FirstName = "Jon",
                            LastName = "Snow",
                            LineManagerId = 5
                        },
                        new
                        {
                            EmployeeId = 7,
                            Email = "TheGreatest@Champ.com",
                            FirstName = "Muhammad",
                            LastName = "Ali",
                            LineManagerId = 5
                        },
                        new
                        {
                            EmployeeId = 8,
                            Email = "ClownPrinceOfCrime@Gotham.com",
                            FirstName = "The",
                            LastName = "Jocker",
                            LineManagerId = 1
                        },
                        new
                        {
                            EmployeeId = 9,
                            Email = "GottaCatchEmAll@Kanto.com",
                            FirstName = "Ash",
                            LastName = "Ketchum",
                            LineManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 10,
                            Email = "ScoobertTheGreat@MysteryMachine.com",
                            FirstName = "Scooby",
                            LastName = "Doo",
                            LineManagerId = 2
                        },
                        new
                        {
                            EmployeeId = 11,
                            Email = "BlackPanther@Wakanda.com",
                            FirstName = "T'Challa",
                            LastName = "Unknown",
                            LineManagerId = 5
                        });
                });

            modelBuilder.Entity("Steamship.Tech.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("SaleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<string>("SaleTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SaleId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            EmployeeId = 10,
                            SaleDescription = "Sold 5000 units of paper to Naruto of the Leaf Village.",
                            SalePrice = 3500.0,
                            SaleTitle = "Naruto paper sale"
                        },
                        new
                        {
                            SaleId = 2,
                            EmployeeId = 4,
                            SaleDescription = "Sold a pair of emerald earrings to Catwoman of Gotham.",
                            SalePrice = 50000.0,
                            SaleTitle = "Catwoman earrings sale"
                        },
                        new
                        {
                            SaleId = 3,
                            EmployeeId = 4,
                            SaleDescription = "Sold a necklace and gold bracelet to Catwoman of Gotham.",
                            SalePrice = 3500.0,
                            SaleTitle = "Catwoman necklace and bracelet sale"
                        },
                        new
                        {
                            SaleId = 4,
                            EmployeeId = 10,
                            SaleDescription = "Sold kryptonite to Lex Luthor of Metropolis.",
                            SalePrice = 3500.0,
                            SaleTitle = "Lex Luthor kryptonite ale"
                        },
                        new
                        {
                            SaleId = 5,
                            EmployeeId = 10,
                            SaleDescription = "arcu ac orci. Ut semper pretium neque. Morbi quis urna.",
                            SalePrice = 50.0,
                            SaleTitle = "amet diam eu dolor."
                        },
                        new
                        {
                            SaleId = 6,
                            EmployeeId = 3,
                            SaleDescription = "hendrerit consectetuer, cursus et, magna.",
                            SalePrice = 608.0,
                            SaleTitle = "taciti sociosqu ad litora torquent per conubia nostra."
                        },
                        new
                        {
                            SaleId = 7,
                            EmployeeId = 3,
                            SaleDescription = "et, rutrum non, hendrerit id, ante. Nunc mauris sapien.",
                            SalePrice = 345.0,
                            SaleTitle = "vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum."
                        },
                        new
                        {
                            SaleId = 10,
                            EmployeeId = 9,
                            SaleDescription = "nulla. In tincidunt congue turpis. In condimentum.",
                            SalePrice = 775.0,
                            SaleTitle = "dapibus rutrum, justo. Praesent luctus."
                        },
                        new
                        {
                            SaleId = 12,
                            EmployeeId = 9,
                            SaleDescription = "Nullam nisl. Maecenas malesuada fringilla est.",
                            SalePrice = 249.0,
                            SaleTitle = "amet, consectetuer adipiscing elit. Etiam laoreet."
                        },
                        new
                        {
                            SaleId = 13,
                            EmployeeId = 11,
                            SaleDescription = "facilisi. Sed neque. Sed eget lacus.",
                            SalePrice = 973.0,
                            SaleTitle = "Curabitur massa. Vestibulum accumsan neque et nunc."
                        },
                        new
                        {
                            SaleId = 15,
                            EmployeeId = 4,
                            SaleDescription = "ornare tortor at risus. Nunc ac sem ut dolor.",
                            SalePrice = 9.0,
                            SaleTitle = "massa non ante bibendum ullamcorper."
                        },
                        new
                        {
                            SaleId = 17,
                            EmployeeId = 9,
                            SaleDescription = "molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris.",
                            SalePrice = 764.0,
                            SaleTitle = "magna. Lorem ipsum dolor sit amet."
                        },
                        new
                        {
                            SaleId = 18,
                            EmployeeId = 11,
                            SaleDescription = "ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris",
                            SalePrice = 29.0,
                            SaleTitle = "primis in faucibus orci luctus et ultrices posuere cubilia Curae."
                        },
                        new
                        {
                            SaleId = 19,
                            EmployeeId = 9,
                            SaleDescription = "bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut.",
                            SalePrice = 677.0,
                            SaleTitle = "Duis sit amet diam eu dolor egestas rhoncus."
                        },
                        new
                        {
                            SaleId = 20,
                            EmployeeId = 10,
                            SaleDescription = "eget ipsum. Suspendisse sagittis. Nullam vitae diam.",
                            SalePrice = 61.0,
                            SaleTitle = "augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo"
                        },
                        new
                        {
                            SaleId = 21,
                            EmployeeId = 6,
                            SaleDescription = "mi, ac mattis velit justo nec ante. Maecenas mi felis.",
                            SalePrice = 346.0,
                            SaleTitle = "odio a purus. Duis elementum, dui quis accumsan convallis."
                        },
                        new
                        {
                            SaleId = 22,
                            EmployeeId = 4,
                            SaleDescription = "Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida.",
                            SalePrice = 750.0,
                            SaleTitle = "augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed."
                        },
                        new
                        {
                            SaleId = 23,
                            EmployeeId = 3,
                            SaleDescription = "penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            SalePrice = 227.0,
                            SaleTitle = "lacus, varius et, euismod et, commodo at, libero."
                        },
                        new
                        {
                            SaleId = 24,
                            EmployeeId = 4,
                            SaleDescription = "montes, nascetur ridiculus mus. Donec dignissim magna a tortor.",
                            SalePrice = 98.0,
                            SaleTitle = "augue ut lacus. Nulla tincidunt, neque vitae semper egestas."
                        });
                });

            modelBuilder.Entity("Steamship.Tech.Entities.Employee", b =>
                {
                    b.HasOne("Steamship.Tech.Entities.Employee", "LineManager")
                        .WithMany()
                        .HasForeignKey("LineManagerId");
                });

            modelBuilder.Entity("Steamship.Tech.Entities.Sale", b =>
                {
                    b.HasOne("Steamship.Tech.Entities.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
